"""Shared physical constants and default policies for the 2-D solver."""


C0 = 299_792_458.0
ETA0 = 376.730313668
EPS = 1e-12
MATERIAL_SINGULAR_TOL = EPS
RCS_DB_FLOOR_LINEAR = EPS
VIRTUAL_SHEET_REGION_START = 900_000
EULER_GAMMA = 0.5772156649015329
CFIE_ALPHA_DEFAULT = 0.0
MAX_PANELS_DEFAULT = 20_000
DEFAULT_PANELS_PER_WAVELENGTH = 20


MIN_EXPLICIT_PANELS_PER_WAVELENGTH = 4


RCS_NORM_NUMERATOR = 0.25
RCS_NORM_MODE_DEFAULT = "physical"
RCS_NORM_MODE_PHYSICAL = "physical"
RCS_AMPLITUDE_CONVENTION = "A_physical_asymptotic = +j * B_stored"
RCS_AMPLITUDE_VERSION = 2
DENSE_LINEAR_BACKWARD_ERROR_MAX = 1.0e-12
DENSE_GPU_BACKEND_ENV = "GHOST_DENSE_BACKEND"
DENSE_GPU_MIN_N_ENV = "GHOST_DENSE_GPU_MIN_N"
DENSE_GPU_MIN_N_DEFAULT = 768
DENSE_GPU_PROBE_TIMEOUT_S = 20.0
